# Generated by Django 5.0.3 on 2024-03-28 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_field', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking_mark', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_or_art', models.CharField(choices=[('Нов', 'Новости'), ('Ст', 'Статья')], default='Нов', max_length=3)),
                ('time_in', models.DateTimeField(auto_now_add=True)),
                ('news_or_art_name', models.CharField(max_length=50)),
                ('news_or_art_text', models.TextField()),
                ('ranking_mark', models.IntegerField(default=0)),
                ('link_Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News_Portal_Project.author')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_com', models.TextField()),
                ('time_in', models.DateTimeField(auto_now_add=True)),
                ('ranking_mark', models.IntegerField(default=0)),
                ('link_Post_User_com', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('link_Post_news_or_art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News_Portal_Project.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_otm_Post_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News_Portal_Project.category')),
                ('link_otm_Post_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News_Portal_Project.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='link_PostCategory',
            field=models.ManyToManyField(through='News_Portal_Project.PostCategory', to='News_Portal_Project.category'),
        ),
    ]
